load("@rules_lilypond//lilypond:defs.bzl", "lilypond_pdf", "lilypond_library", "lilypond_parts_pdfs", "lilypond_book")

TITLE = "Excerpt from the 7th Symphony"
COMPOSER = "Gustav Mahler"

lilypond_pdf(
    name = "score",
    deps = [":score_book"],
)

#lilypond_parts_pdfs(
#    name = "parts",
#    title = TITLE,
#    composer = COMPOSER,
#    warning_as_error = False,  # TODO: Fix "decrescendo too small".
#    deps = [
#        ":tpt1",
#        ":tpt2",
#        ":tpt3",
#    ],
#)

lilypond_book(
    name = "score_book",
    skip_bars = False,
    title = TITLE,
    composer = COMPOSER,
    deps = [
        ":tpt1",
        ":tpt2",
        ":tpt3",
    ],
)

lilypond_library(
    name = "tpt1",
    srcs = ["tpt1-notes.ly"],
    music_var = "tptOne",
    instrument = "Trumpet I in Bb",
    short_instrument = "Tpt I",
)

lilypond_library(
    name = "tpt2",
    srcs = ["tpt2-notes.ly"],
    music_var = "tptTwo",
    instrument = "Trumpet II in Bb",
    short_instrument = "Tpt II",
)

lilypond_library(
    name = "tpt3",
    srcs = ["tpt3-notes.ly"],
    music_var = "tptThree",
    instrument = "Trumpet III in Bb",
    short_instrument = "Tpt III",
)
